name: "Build and Publish, Deploy Docker Image"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "preview"
    paths:
      - "**"
      - "!.github/**"

jobs:
  build-publish:
    uses: chnm/.github/.github/workflows/django--build-publish.yml@main
    secrets: inherit
    with:
      container-registry: "ghcr.io"
      container-image-name: "religious-ecologies"

      django-context-root: "."

      website-devl-fqdn: "dev.database.religiousecologies.org"
      website-prod-fqdn: "database.religiousecologies.org"

  deploy:
    uses: chnm/.github/.github/workflows/django--deploy.yml@main
    needs: [build-publish]
    secrets: inherit
    with:
      website-devl-fqdn: "dev.database.religiousecologies.org"
      website-prod-fqdn: "database.religiousecologies.org"
